"""Ask Omni — the multi-agent deliberation layer.

Two execution paths, same output contract:

- If ANTHROPIC_API_KEY is set, the six specialist positions and the final
  verdict are generated by Claude, given the user's actual stored vitals,
  twin nodes, and findings as context.
- Otherwise a deterministic clinical reasoning engine derives the same
  structure from those same rows.

The second path is not a stub or canned text: every position is computed from
the querying user's own database records, so two accounts produce genuinely
different deliberations. It exists because the API key is deployment
configuration, and the feature should not be dark without one.

Consent is enforced before either path sees anything (SRS §6.2): a scope the
user has revoked is filtered out of the context, and the agents are told the
data was withheld rather than being given it silently.
"""

import json
import os

from .extensions import db
from .models import ClinicalFinding, ConsentScope, Predisposition, TwinNode, VitalReading

SPECIALISTS = [
    ("cardiology", "Cardiology", "heart"),
    ("endocrinology", "Endocrinology", "activity"),
    ("neurology", "Neurology", "brain"),
    ("nephrology", "Nephrology", "droplet"),
    ("immunology", "Immunology", "shield"),
    ("lifestyle", "Lifestyle Medicine", "leaf"),
]

# Presentations that must bypass the clarifying-question flow entirely.
# SRS gap #1 called out the absence of this; it is enforced here rather than
# left to the model's judgement.
RED_FLAGS = [
    ("chest pain", "Chest pain"),
    ("chest tightness", "Chest tightness"),
    ("crushing", "Crushing chest sensation"),
    ("can't breathe", "Acute breathlessness"),
    ("cant breathe", "Acute breathlessness"),
    ("short of breath", "Acute breathlessness"),
    ("slurred", "Slurred speech"),
    ("face drooping", "Facial droop"),
    ("one side", "Unilateral weakness"),
    ("numb on", "Unilateral numbness"),
    ("worst headache", "Thunderclap headache"),
    ("unconscious", "Loss of consciousness"),
    ("fainted", "Syncope"),
    ("coughing blood", "Haemoptysis"),
    ("vomiting blood", "Haematemesis"),
    ("suicid", "Suicidal ideation"),
]


def check_red_flags(text):
    lowered = (text or "").lower()
    hits = [label for token, label in RED_FLAGS if token in lowered]
    return sorted(set(hits))


def gather_context(user_id):
    """Assemble the clinical picture, filtered through granted consent."""
    granted = {
        row.key
        for row in db.session.query(ConsentScope).filter_by(user_id=user_id, granted=True)
    }
    withheld = {
        row.key
        for row in db.session.query(ConsentScope).filter_by(user_id=user_id, granted=False)
    }

    context = {"granted": sorted(granted), "withheld": sorted(withheld)}

    if "lifestyle" in granted:
        recent = (
            db.session.query(VitalReading)
            .filter_by(user_id=user_id)
            .order_by(VitalReading.recorded_on.desc())
            .limit(14)
            .all()
        )
        if recent:
            context["vitals"] = {
                "latest": recent[0].to_dict(),
                "meanHeartRate": round(sum(v.heart_rate for v in recent) / len(recent), 1),
                "meanHrv": round(sum(v.hrv_ms for v in recent) / len(recent), 1),
                "meanSleep": round(sum(v.sleep_hours for v in recent) / len(recent), 2),
                "meanStress": round(sum(v.stress_score for v in recent) / len(recent), 1),
                "meanHydration": round(sum(v.hydration_ml for v in recent) / len(recent)),
                "days": len(recent),
            }

    if "digital_twin" in granted:
        nodes = db.session.query(TwinNode).filter_by(user_id=user_id).all()
        context["twin"] = {n.key: {"risk": n.risk_pct, "status": n.status} for n in nodes}

    if "records" in granted:
        finding = (
            db.session.query(ClinicalFinding)
            .filter_by(user_id=user_id)
            .order_by(ClinicalFinding.created_at.desc())
            .first()
        )
        if finding:
            context["activeFinding"] = finding.to_dict()

    if "family_history" in granted:
        context["predispositions"] = [
            p.to_dict() for p in db.session.query(Predisposition).filter_by(user_id=user_id)
        ]

    return context


# ---------------------------------------------------------------------------
# Deterministic reasoning engine
# ---------------------------------------------------------------------------

def _position(key, label, icon, stance, statement, confidence):
    return {
        "key": key,
        "specialty": label,
        "icon": icon,
        "stance": stance,          # concur | dissent | abstain
        "statement": statement,
        "confidence": confidence,
    }


def deliberate_locally(question, context):
    """Derive six specialist positions from the user's own stored data."""
    vitals = context.get("vitals")
    twin = context.get("twin", {})
    positions = []

    def risk_of(key):
        return twin.get(key, {}).get("risk")

    # --- Cardiology ---
    heart_risk = risk_of("heart")
    if vitals and heart_risk is not None:
        hr, hrv = vitals["meanHeartRate"], vitals["meanHrv"]
        if heart_risk >= 45 or hr > 78:
            positions.append(_position(
                "cardiology", "Cardiology", "heart", "concur",
                f"14-day mean resting heart rate is {hr} bpm with HRV at {hrv} ms. "
                f"Cardiovascular load scores {heart_risk}%. This warrants ambulatory blood pressure monitoring.",
                "high" if heart_risk >= 55 else "moderate",
            ))
        else:
            positions.append(_position(
                "cardiology", "Cardiology", "heart", "dissent",
                f"Resting heart rate ({hr} bpm) and HRV ({hrv} ms) sit within your own baseline. "
                "I would not attribute the presentation to cardiac strain.",
                "moderate",
            ))
    else:
        positions.append(_position(
            "cardiology", "Cardiology", "heart", "abstain",
            "No wearable or cardiovascular data available under current consent. I cannot form a position.",
            "none",
        ))

    # --- Endocrinology ---
    metabolic_risk = risk_of("metabolic")
    if metabolic_risk is not None:
        if metabolic_risk >= 40:
            positions.append(_position(
                "endocrinology", "Endocrinology", "activity", "concur",
                f"Metabolic system scores {metabolic_risk}%. Glucose handling is the more likely driver here; "
                "an HbA1c and fasting insulin would settle it.",
                "moderate",
            ))
        else:
            positions.append(_position(
                "endocrinology", "Endocrinology", "activity", "dissent",
                f"Metabolic markers score {metabolic_risk}%, which is unremarkable. "
                "I see no endocrine contribution worth pursuing first.",
                "moderate",
            ))
    else:
        positions.append(_position(
            "endocrinology", "Endocrinology", "activity", "abstain",
            "Digital twin modelling is not consented, so metabolic scoring is unavailable.",
            "none",
        ))

    # --- Neurology ---
    if vitals:
        sleep, stress = vitals["meanSleep"], vitals["meanStress"]
        if sleep < 6.5 or stress > 55:
            positions.append(_position(
                "neurology", "Neurology", "brain", "concur",
                f"Sleep averages {sleep} h against a {stress}/100 stress load. Chronic sleep debt of this depth "
                "produces exactly this symptom cluster and compounds every other system here.",
                "high",
            ))
        else:
            positions.append(_position(
                "neurology", "Neurology", "brain", "dissent",
                f"Sleep ({sleep} h) and stress ({stress}/100) are adequate. "
                "I disagree that this is fatigue-driven — look elsewhere first.",
                "moderate",
            ))
    else:
        positions.append(_position(
            "neurology", "Neurology", "brain", "abstain",
            "Sleep and stress data are withheld under current consent settings.",
            "none",
        ))

    # --- Nephrology ---
    if vitals:
        hydration = vitals["meanHydration"]
        if hydration < 1800:
            positions.append(_position(
                "nephrology", "Nephrology", "droplet", "concur",
                f"Hydration averages {hydration} ml/day, well under target. This alone can produce the "
                "presentation and is the cheapest thing on this list to correct.",
                "moderate",
            ))
        else:
            positions.append(_position(
                "nephrology", "Nephrology", "droplet", "abstain",
                f"Hydration at {hydration} ml/day is adequate. Without serum creatinine or eGFR "
                "I have no basis for a renal position.",
                "none",
            ))
    else:
        positions.append(_position(
            "nephrology", "Nephrology", "droplet", "abstain",
            "No hydration or renal data available under current consent.",
            "none",
        ))

    # --- Immunology ---
    immune_risk = risk_of("immune")
    if immune_risk is not None and immune_risk >= 40:
        positions.append(_position(
            "immunology", "Immunology", "shield", "concur",
            f"Immune resilience scores {immune_risk}%. With regional influenza activity elevated, "
            "recovery capacity is worth checking with a CBC.",
            "moderate",
        ))
    else:
        positions.append(_position(
            "immunology", "Immunology", "shield", "abstain",
            "Nothing in the available data points to an immune contribution. I defer to the others.",
            "none",
        ))

    # --- Lifestyle Medicine ---
    if vitals:
        positions.append(_position(
            "lifestyle", "Lifestyle Medicine", "leaf", "concur",
            f"Before any investigation: sleep is {vitals['meanSleep']} h and hydration {vitals['meanHydration']} ml. "
            "Correcting those two for three weeks would change the interpretation of every other finding here.",
            "high",
        ))
    else:
        positions.append(_position(
            "lifestyle", "Lifestyle Medicine", "leaf", "abstain",
            "Lifestyle data is withheld, so I cannot advise on modifiable factors.",
            "none",
        ))

    return positions


def build_verdict(positions, context, red_flags):
    """Stage a plan from the positions. Abstains outnumbering concurs is an
    explicit 'I don't know yet', not a fabricated answer."""
    if red_flags:
        return {
            "abstained": False,
            "urgent": True,
            "summary": "This needs to be assessed in person now, not by me.",
            "stages": [
                {"stage": "Immediately", "actions": [
                    "Use the SOS control or call 108 for emergency transport.",
                    "Do not drive yourself.",
                ]},
                {"stage": "On arrival", "actions": [
                    "Tell them which symptoms started and when.",
                    "Mention any cardiac or neurological history.",
                ]},
            ],
            "flags": red_flags,
        }

    concurring = [p for p in positions if p["stance"] == "concur"]
    abstaining = [p for p in positions if p["stance"] == "abstain"]

    if len(abstaining) >= 4 or not concurring:
        return {
            "abstained": True,
            "urgent": False,
            "summary": "I don't know yet — there isn't enough data to reason from.",
            "detail": (
                "Most of the panel abstained. Either the consent scopes needed for this question "
                "are switched off, or there aren't enough readings on record yet. "
                "Granting the relevant scope or uploading a recent report would let me answer properly."
            ),
            "stages": [],
        }

    ranked = sorted(
        concurring,
        key=lambda p: {"high": 0, "moderate": 1, "none": 2}[p["confidence"]],
    )
    lead = ranked[0]

    stages = [
        {"stage": "This week", "actions": [
            f"Act on {lead['specialty']}'s read first — it carries the most support in the panel.",
            "Log sleep and hydration daily so the next deliberation has cleaner inputs.",
        ]},
        {"stage": "Next two weeks", "actions": [
            a for a in (context.get("activeFinding", {}).get("suggestedNext") or [])
        ] or ["Book a general physician review to order baseline bloods."]},
        {"stage": "Then", "actions": [
            "Re-run this question — the twin updates as new readings land.",
        ]},
    ]

    dissent = [p for p in positions if p["stance"] == "dissent"]
    return {
        "abstained": False,
        "urgent": False,
        "summary": f"{len(concurring)} of 6 specialists converge on {lead['specialty'].lower()} as the lead thread.",
        "dissentNote": (
            f"{dissent[0]['specialty']} disagrees — worth reading their position before you commit."
            if dissent else None
        ),
        "stages": stages,
    }


# ---------------------------------------------------------------------------
# Claude path
# ---------------------------------------------------------------------------

def claude_available():
    return bool(os.environ.get("ANTHROPIC_API_KEY"))


DELIBERATION_SCHEMA = {
    "type": "object",
    "properties": {
        "followUp": {"type": "string"},
        "whyAsking": {"type": "string"},
        "positions": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "key": {"type": "string"},
                    "specialty": {"type": "string"},
                    "icon": {"type": "string"},
                    "stance": {"type": "string", "enum": ["concur", "dissent", "abstain"]},
                    "statement": {"type": "string"},
                    "confidence": {"type": "string", "enum": ["high", "moderate", "none"]},
                },
                "required": ["key", "specialty", "icon", "stance", "statement", "confidence"],
                "additionalProperties": False,
            },
        },
    },
    "required": ["followUp", "whyAsking", "positions"],
    "additionalProperties": False,
}

SYSTEM_PROMPT = """You are Omni, the clinical reasoning layer of OmniCare.

Six specialists deliberate on each question: cardiology, endocrinology, neurology,
nephrology, immunology, and lifestyle medicine. They are allowed to disagree, and a
specialist with no basis for a position must abstain rather than invent one.

Ground every statement in the numbers you are given. Never state a figure that is not
in the context. If a consent scope was withheld, the specialists who depend on it
abstain and say the data was not available — do not speculate around the gap.

Frame risk as worth attention rather than as emergency. Speak plainly; avoid jargon
unless it is the precise term."""


def deliberate_with_claude(question, context, history):
    """Generate the panel via Claude. Raises on failure so the caller can fall back."""
    import anthropic

    client = anthropic.Anthropic()
    transcript = "\n".join(f"{m['role']}: {m['body']}" for m in history[-6:])

    response = client.messages.create(
        model="claude-opus-5",
        max_tokens=16000,
        system=SYSTEM_PROMPT,
        thinking={"type": "adaptive"},
        output_config={"format": {"type": "json_schema", "schema": DELIBERATION_SCHEMA}},
        messages=[{
            "role": "user",
            "content": (
                f"Clinical context (from this patient's records):\n{json.dumps(context, indent=2)}\n\n"
                f"Recent conversation:\n{transcript or '(none)'}\n\n"
                f"Patient asks: {question}"
            ),
        }],
    )

    for block in response.content:
        if block.type == "text":
            return json.loads(block.text)
    raise RuntimeError("Claude returned no text block")


def respond(question, context, history):
    """Produce one Omni turn. Returns (body, blocks)."""
    red_flags = check_red_flags(question)

    if red_flags:
        # Red flags short-circuit the whole deliberation flow.
        return (
            "Stop — this needs urgent in-person assessment.",
            {
                "redFlags": red_flags,
                "deliberation": [],
                "verdict": build_verdict([], context, red_flags),
                "engine": "red-flag-triage",
            },
        )

    engine = "local-reasoning"
    follow_up = None
    why_asking = None
    positions = None

    if claude_available():
        try:
            result = deliberate_with_claude(question, context, history)
            positions = result["positions"]
            follow_up = result.get("followUp")
            why_asking = result.get("whyAsking")
            engine = "claude-opus-5"
        except Exception:
            positions = None  # fall through to local engine

    if positions is None:
        positions = deliberate_locally(question, context)
        follow_up = "How many days has this been going on, and is it worse at any particular time?"
        why_asking = (
            "Duration and timing separate the systems above faster than any single test would."
        )

    verdict = build_verdict(positions, context, red_flags)

    return (
        "Here's how the panel read your question.",
        {
            "followUp": follow_up,
            "whyAsking": why_asking,
            "deliberation": positions,
            "verdict": verdict,
            "withheldScopes": context.get("withheld", []),
            "engine": engine,
        },
    )
