"""add clinical, catalogue and activity tables

Revision ID: 736b203dee7d
Revises: ea760f1cccae
Create Date: 2026-08-08 19:05:32.484688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736b203dee7d'
down_revision = 'ea760f1cccae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_workers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('worker_type', sa.String(length=40), nullable=False),
    sa.Column('role_label', sa.String(length=80), nullable=False),
    sa.Column('rate_per_hour_inr', sa.Integer(), nullable=False),
    sa.Column('availability', sa.String(length=40), nullable=False),
    sa.Column('experience_note', sa.String(length=200), nullable=False),
    sa.Column('photo_seed', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('care_workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_care_workers_worker_type'), ['worker_type'], unique=False)

    op.create_table('doctors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('specialty', sa.String(length=80), nullable=False),
    sa.Column('hospital', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('fee_inr', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviews', sa.Integer(), nullable=False),
    sa.Column('next_slot', sa.String(length=60), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('photo_seed', sa.String(length=40), nullable=False),
    sa.Column('supports_video', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_specialty'), ['specialty'], unique=False)

    op.create_table('medicines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('generic_salt', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('price_inr', sa.Integer(), nullable=False),
    sa.Column('requires_prescription', sa.Boolean(), nullable=False),
    sa.Column('delivery_eta', sa.String(length=40), nullable=False),
    sa.Column('pack_size', sa.String(length=60), nullable=False),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicines_category'), ['category'], unique=False)

    op.create_table('outbreak_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('condition', sa.String(length=120), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=False),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('air_quality_index', sa.Integer(), nullable=False),
    sa.Column('air_quality_note', sa.String(length=200), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbreak_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbreak_signals_city'), ['city'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_user_id'), ['user_id'], unique=False)

    op.create_table('cart_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_items_user_id'), ['user_id'], unique=False)

    op.create_table('clinical_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=False),
    sa.Column('suspected_condition', sa.String(length=160), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('reasoning_json', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=40), nullable=False),
    sa.Column('suggested_next_json', sa.Text(), nullable=False),
    sa.Column('saved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_findings_user_id'), ['user_id'], unique=False)

    op.create_table('consent_scopes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_scopes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_scopes_user_id'), ['user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('predispositions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('condition', sa.String(length=120), nullable=False),
    sa.Column('probability_pct', sa.Float(), nullable=False),
    sa.Column('drivers_json', sa.Text(), nullable=False),
    sa.Column('lever', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predispositions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predispositions_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('twin_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('risk_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('x_pct', sa.Float(), nullable=False),
    sa.Column('y_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('twin_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_twin_nodes_user_id'), ['user_id'], unique=False)

    op.create_table('twin_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('biological_age', sa.Float(), nullable=False),
    sa.Column('actual_age', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('twin_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_twin_summaries_user_id'), ['user_id'], unique=False)

    op.create_table('vital_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=False),
    sa.Column('hrv_ms', sa.Integer(), nullable=False),
    sa.Column('spo2', sa.Integer(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=False),
    sa.Column('stress_score', sa.Integer(), nullable=False),
    sa.Column('hydration_ml', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vital_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vital_readings_recorded_on'), ['recorded_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_vital_readings_user_id'), ['user_id'], unique=False)

    op.create_table('biomarkers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('reference_range', sa.String(length=60), nullable=False),
    sa.Column('flag', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biomarkers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biomarkers_report_id'), ['report_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('blocks_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('biomarkers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biomarkers_report_id'))

    op.drop_table('biomarkers')
    with op.batch_alter_table('vital_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vital_readings_user_id'))
        batch_op.drop_index(batch_op.f('ix_vital_readings_recorded_on'))

    op.drop_table('vital_readings')
    with op.batch_alter_table('twin_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twin_summaries_user_id'))

    op.drop_table('twin_summaries')
    with op.batch_alter_table('twin_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twin_nodes_user_id'))

    op.drop_table('twin_nodes')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))

    op.drop_table('reports')
    with op.batch_alter_table('predispositions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predispositions_user_id'))

    op.drop_table('predispositions')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('consent_scopes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_scopes_user_id'))

    op.drop_table('consent_scopes')
    with op.batch_alter_table('clinical_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_findings_user_id'))

    op.drop_table('clinical_findings')
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_items_user_id'))

    op.drop_table('cart_items')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_user_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('outbreak_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbreak_signals_city'))

    op.drop_table('outbreak_signals')
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicines_category'))

    op.drop_table('medicines')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_specialty'))

    op.drop_table('doctors')
    with op.batch_alter_table('care_workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_care_workers_worker_type'))

    op.drop_table('care_workers')
    # ### end Alembic commands ###
