"""remove generated clinical tables; biomarker source

Revision ID: dbdde4104cc7
Revises: 736b203dee7d
Create Date: 2026-08-08 19:56:29.273567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdde4104cc7'
down_revision = '736b203dee7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twin_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twin_nodes_user_id'))

    op.drop_table('twin_nodes')
    with op.batch_alter_table('predispositions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predispositions_user_id'))

    op.drop_table('predispositions')
    with op.batch_alter_table('clinical_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_findings_user_id'))

    op.drop_table('clinical_findings')
    with op.batch_alter_table('twin_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twin_summaries_user_id'))

    op.drop_table('twin_summaries')
    with op.batch_alter_table('biomarkers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biomarkers', schema=None) as batch_op:
        batch_op.drop_column('source')

    op.create_table('twin_summaries',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('health_score', sa.INTEGER(), nullable=False),
    sa.Column('biological_age', sa.FLOAT(), nullable=False),
    sa.Column('actual_age', sa.INTEGER(), nullable=False),
    sa.Column('model_version', sa.VARCHAR(length=20), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('twin_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_twin_summaries_user_id'), ['user_id'], unique=False)

    op.create_table('clinical_findings',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('headline', sa.VARCHAR(length=200), nullable=False),
    sa.Column('suspected_condition', sa.VARCHAR(length=160), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=30), nullable=False),
    sa.Column('reasoning_json', sa.TEXT(), nullable=False),
    sa.Column('risk_score', sa.FLOAT(), nullable=False),
    sa.Column('risk_band', sa.VARCHAR(length=40), nullable=False),
    sa.Column('suggested_next_json', sa.TEXT(), nullable=False),
    sa.Column('saved', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_findings_user_id'), ['user_id'], unique=False)

    op.create_table('predispositions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('condition', sa.VARCHAR(length=120), nullable=False),
    sa.Column('probability_pct', sa.FLOAT(), nullable=False),
    sa.Column('drivers_json', sa.TEXT(), nullable=False),
    sa.Column('lever', sa.VARCHAR(length=300), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predispositions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predispositions_user_id'), ['user_id'], unique=False)

    op.create_table('twin_nodes',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('key', sa.VARCHAR(length=30), nullable=False),
    sa.Column('label', sa.VARCHAR(length=60), nullable=False),
    sa.Column('risk_pct', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('note', sa.VARCHAR(length=300), nullable=False),
    sa.Column('x_pct', sa.FLOAT(), nullable=False),
    sa.Column('y_pct', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('twin_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_twin_nodes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
